### ISSUE TITLE
Stop letting the founder touch code issues

### ISSUE THREAD

**Issue by AndruC** [HumanityInc/Humanity#7]
Max is closing issues that he is not contributing to. He is closing legitimate issues (https://github.com/HumanityInc/Humanity/issues/6) because "he does not have the time". 

Why is a non-developer touching these issues in the first place? He tries to turn legitimate bug reports into marketing ads. GitHub is not the place for telling us how busy you are.

Leave the development to the professionals.

**Comment by HumanBe1ng** [comment]
Andrew this is the 4th bullshit "issue" you have started (from this or your two fake accounts, for which github has the matching IP). You are wasting everybody's time. You have contributed ZERO to the development of our company, and have been working NON stop to make our lives as difficult as possible. Issue #6 was closed because, as CLEARLY stated there, it was added to our work log. Stop lying, and stop wasting everybody's time. We are tired of your crap. One more post like this and you will be permanently banned (github offered to do this last time and I asked them not to). Next time you won't get a free pass. I have removed you from our git.

**Comment by Max-Human** [comment]
Oh, I just remembered that you created TWO fake accounts (github has the IPs) to post some of the previous bullshit issues. Get help man. I mean it. Get help. We obviously made a mistake by letting you back here because you just can't help yourself. Some people help, others just run their mouth and get in the way. Don't come back.
